import Head from "next/head";
import React from "react";

import styles from "./About.module.css";

const AboutPage = () => {
  return (
    <div className={styles.AboutPageContainer}>
      <Head>
        <title>About Us </title>
        <meta name="About Us" content="Generated by create next app" />
      </Head>

      <main className={styles.Main}>
        <div className={styles.TitleContainer}>
          <h1 className={styles.Title}>
            About <span>Runo</span>
          </h1>
        </div>

        <div className={styles.Body}>
          <p className={styles.Description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
            viverra vitae ligula in vulputate. Quisque lacinia sapien nunc, at
            dictum erat eleifend eu. Ut sed velit mattis, lacinia ante eu,
            malesuada lorem. Suspendisse eget facilisis enim. Morbi quis
            placerat purus. Duis eget nulla eget velit porttitor venenatis
            maximus sit amet orci. Donec sagittis ante mauris, a pharetra quam
            facilisis ac. Praesent feugiat nunc nec tincidunt suscipit. Vivamus
            at nulla eget erat iaculis consequat. Duis a mauris enim. In
            malesuada augue in neque porttitor ultrices non id est. Curabitur
            dolor nisl, luctus in semper vitae, placerat iaculis nibh. Donec a
            lacinia leo. Fusce semper at ante id dapibus. Aenean id erat at
            justo ultrices iaculis.
          </p>
          <p className={styles.Description}>
            Cras iaculis leo at elit bibendum, nec consectetur lorem
            scelerisque. Cras condimentum diam orci, sollicitudin facilisis est
            tincidunt vel. In non lobortis leo. Nam ut libero quis lacus
            facilisis aliquet malesuada porta mauris. Vivamus accumsan lacus in
            mi fermentum convallis sit amet quis ex. Nam luctus metus a tortor
            fringilla fermentum. Aliquam ac consectetur magna. Cras sit amet
            velit dapibus, luctus massa quis, laoreet tellus. Etiam tincidunt
            purus a libero euismod, id ornare leo commodo. Nam a vehicula mi.
            Vivamus blandit semper mollis. Aenean varius finibus risus ac
            commodo. Donec sed leo ac lacus lacinia tempus ut a massa.
          </p>
        </div>
      </main>
    </div>
  );
};

export default AboutPage;
